import React from 'react';
import Button from '@mui/material/Button';
import Stack from '@mui/material/Stack';
import { Link } from 'react-router-dom';
import IconButton from '@mui/material/IconButton';
import HomeIcon from '@mui/icons-material/Home';
import Radio from '@mui/material/Radio';
import RadioGroup from '@mui/material/RadioGroup';
import FormControlLabel from '@mui/material/FormControlLabel';
import FormControl from '@mui/material/FormControl';
import FormLabel from '@mui/material/FormLabel';


const Sample2 = (props) => {

	return (
		<>
			<h1>Labeling Criteria and Examples</h1>
      <h2>Here are labeling examples.</h2>
      <div className='example'>
			<ul>
			<h2>&nbsp;</h2>
        <li>
		<h2 style={{fontWeight: "normal"}}>Example 1: Got the earphones 3 days back.</h2>
        </li>
		<table>
					<th></th>
					<th style={{fontWeight: "normal"}}>True</th>
					<th style={{fontWeight: "normal"}}>False</th>
					<tr>
						<td><b>
							Consideration
						</b></td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="0"							
							checked="checked"							
						>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Purchase

						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"	
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Shipping
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							checked="checked"							
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Using
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio"  
							value="0"
							checked="checked"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Customer Service
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio"
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>None
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"							
							checked="checked"							
							>
							</input>
						</td>
					</tr>
				</table> 
				<h2>&nbsp;</h2>
        <li>
		<h2 style={{fontWeight: "normal"}}>Example 2:  After a long research to get my BT Headset in the price rage of Rs.2000, I finally landed with this one</h2>
          </li>
		  <table>
					<th></th>
					<th style={{fontWeight: "normal"}}>True</th>
					<th style={{fontWeight: "normal"}}>False</th>
					<tr>
						<td><b>
							Consideration
						</b></td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="1"
							checked="checked"							
							>
							</input>
						</td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="0"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Purchase

						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							checked="checked"							
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Shipping
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Using
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio"  
							value="0"
							checked="checked"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Customer Service
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio"
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"							
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>None
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"														
							>
							</input>
						</td>
					</tr>
				</table>
				<h2>&nbsp;</h2>
				
				<li>
		<h2 style={{fontWeight: "normal"}}>Example 3 : I returned the headset because of the poor sound quality.</h2>
          </li>
		  <table>
					<th></th>
					<th style={{fontWeight: "normal"}}>True</th>
					<th style={{fontWeight: "normal"}}>False</th>
					<tr>
						<td><b>
							Consideration
						</b></td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Purchase

						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"							

							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Shipping
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"							

							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Using
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							checked="checked"							
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio"  
							value="0"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Customer Service
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio"
							value="1"
							checked="checked"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>None
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"							
							checked="checked"
							>
							</input>
						</td>
					</tr>
				</table>
		<h2>&nbsp;</h2>
        <li>
		<h2 style={{fontWeight: "normal"}}>Example 4 : This is one of the top ones.</h2>
          </li>
		  <table>
					<th></th>
					<th style={{fontWeight: "normal"}}>True</th>
					<th style={{fontWeight: "normal"}}>False</th>
					<tr>
						<td><b>
							Consideration
						</b></td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
							<input 
							className="bigButton"
							type="radio" 
							value="0"							
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Purchase

						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Shipping
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Using
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio"  
							value="0"
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>Customer Service
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio"
							value="1"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"
							checked="checked"
							>
							</input>
						</td>
					</tr>
					<tr>
						<td><b>None
						</b></td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="1"
							checked="checked"
							>
							</input>
						</td>
						<td>
						<input 
							className="bigButton"
							type="radio" 
							value="0"							>
							</input>
						</td>
					</tr>
				</table>      </ul>
      </div>
			<Stack direction="row" spacing={2}>
        <Link to="/">
				  <Button variant="outlined">Previous</Button>
        </Link>
        <Link to="/problem">
				  <Button variant="outlined">Next</Button>
        </Link>
			</Stack>
		</>
	);
};

export default Sample2;
